# Generated by Django 3.0.2 on 2020-01-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_options',
            field=models.CharField(choices=[('1', 'Free shipping'), ('2', 'Express shipping'), ('3', 'Courier shipping'), ('4', 'Free Express shipping')], max_length=100),
        ),
    ]
