# Generated by Django 3.0.2 on 2020-01-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20200120_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_options',
            field=models.CharField(choices=[('1', 'Free shipping +0.0$'), ('2', 'Express shipping +9.99$'), ('3', 'Courier shipping +19.99$'), ('4', 'Free Express shipping')], max_length=100),
        ),
    ]
